With join_gr5 As(
  SELECT DISTINCT
    s.stu_id,
    s.stu_deg_lev,
    s.stu_adm_date,
    s.stu_adm_year,
    s.stu_adm_term,
    s.sta_pres_id,
    s.sta_pres_des,
    s.stu_comp_date,
    s.stu_comp_year,
    s.stu_comp_term,
    s.stu_sex,
    s.stu_gpa_old,
    s.deg_lev_id,
    s.deg_lev_nth,
    s.fac_id,
    s.fac_nth_f,
    s.Cur_Type,
    s.cur_id,
    s.cur_rn,
    s.Study_Type,
    s.cur_nth,
    s.stu_app_plan,
    s.stu_prg_plan,
    s.stu_plan,
    s.pattern_detail,
    s.Brn_ID,
    s.brn_deg_nth,
    s.Sub_Brn_ID,
    s.Sub_Brn_Nth,
    s.max_year,
    s.Bench_id, 
    s.criteria,
    s.occup_id,
    s.occup_name,
    s.groupN_id,
    s.study_group_type,
    s.thesis_lang,
    s.uni_id,
    s.uni_nth,
    s.nat_id,
    s.nat_nth,
    s.province_id,
    s.province_name_th,
    s.deform_id,
    s.DEFORM_NAME,
    s.Job_Status,
    s.Student_Type,
    s.student_des,
    s.Grad_mean_Sum,
    s.Credit_Calt_Sum,
    s.Credit_Term_Sum,
    s.Grad_mean_Year,
    s.Grad_mean_Term,
    s.Date_Mean,
    s.payment_calculation_type_id,
    s.payment_calculation_type_name_th,
    s.stu_birth,
    s.thesis_name_en,
    s.thesis_name_th,
    t.submit_date_key AS grad_request_date
FROM {{ref('silver_student_data')}} s
Left Join silver_thesis_data t
  ON s.stu_id = t.stu_id
  AND t.Id_form = '22'

),

join_dim_date AS(
  Select 
    s.stu_id,
    s.stu_deg_lev,
    s.stu_adm_date,
    s.stu_adm_year,
    s.stu_adm_term,
    s.sta_pres_id,
    s.sta_pres_des,
    s.stu_comp_date,
    s.stu_comp_year,
    s.stu_comp_term,
    s.stu_sex,
    s.stu_gpa_old,
    s.deg_lev_id,
    s.deg_lev_nth,
    s.fac_id,
    s.fac_nth_f,
    s.Cur_Type,
    s.cur_id,
    s.cur_rn,
    s.Study_Type,
    s.cur_nth,
    s.stu_app_plan,
    s.stu_prg_plan,
    s.stu_plan,
    s.pattern_detail,
    s.Brn_ID,
    s.brn_deg_nth,
    s.Sub_Brn_ID,
    s.Sub_Brn_Nth,
    s.max_year,
    s.Bench_id, 
    s.criteria,
    s.occup_id,
    s.occup_name,
    s.groupN_id,
    s.study_group_type,
    s.thesis_lang,
    s.uni_id,
    s.uni_nth,
    s.nat_id,
    s.nat_nth,
    s.province_id,
    s.province_name_th,
    s.deform_id,
    s.DEFORM_NAME,
    s.Job_Status,
    s.Student_Type,
    s.student_des,
    s.Grad_mean_Sum,
    s.Credit_Calt_Sum,
    s.Credit_Term_Sum,
    s.Grad_mean_Year,
    s.Grad_mean_Term,
    s.Date_Mean,
    s.payment_calculation_type_id,
    s.payment_calculation_type_name_th,
    s.stu_birth,
    s.thesis_name_en,
    s.thesis_name_th,  
    dd.date_display as grad_request_date  
  From join_gr5 s
  LEFT JOIN dim_date dd
    ON  s.grad_request_date = dd.date_key
)

Select * from join_dim_date
