INSERT INTO bronze.curriculum(
   cur_id,
   cur_rn,
   study_type,
   deg_lev_id,
   [ชื่อหลักสูตร (th) ],
   [ชื่อหลักสูตร (en) ],
   [ระดับ],
   fac_id,
   [คณะ (th) ],
   [คณะ (en) ],
   cur_pla_a1,
   cur_pla_a2,
   cur_pla_b ,
   cur_pla_1_1,
   cur_pla_1_2,
   cur_pla_2_1,
   cur_pla_2_2,
   [เว็บไซต์ ],
   [ชื่่อปริญญา (th) ],
   [ชื่่อปริญญา (en) ],
   Brn_ID,
   Sub_Brn_ID,
   [วิชาเอก (th) ],
   [วิชาเอก (en) ],
   [จุดเด่นของหลักสูตร (th) ],
   [จุดเด่นของหลักสูตร (en) ],
   [คุณสมบัติของผุู้เข้าศึกษา (th) ],
   [คุณสมบัติของผุู้เข้าศึกษา (en) ] ,
   cur_type_th,
   cur_type_i,
   cur_desth,
   [อาชีพที่สามารถประกอบได้หลังสำเร็จการศึกษา (th) ] ,
   [อาชีพที่สามารถประกอบได้หลังสำเร็จการศึกษา (en) ] ,
   groupN_id ,
   [กลุ่มการศึกษาแบ่งตามมหาวิทยาลัย (3 กลุ่ม) ],
   [ภาษาที่ใช้ทำวิทยานิพนธ์ (T/E) ] 
)
SELECT
    sc.cur_id,
    sc.cur_rn,
    sc.study_type,
    sc.deg_lev_id,
    sc.[ชื่อหลักสูตร (th) ],
    sc.[ชื่อหลักสูตร (en) ],
    sc.ระดับ,
    sc.fac_id,
    sc.[คณะ (th) ]  ,
    sc.[คณะ (en) ]  ,
    sc.cur_pla_a1,
    sc.cur_pla_a2,
    sc.cur_pla_b ,
    sc.cur_pla_1_1,
    sc.cur_pla_1_2,
    sc.cur_pla_2_1,
    sc.cur_pla_2_2,
    sc.[เว็บไซต์ ]   ,
    sc.[ชื่่อปริญญา (th) ],
    sc.[ชื่่อปริญญา (en) ],
    sc.Brn_ID,
    sc.Sub_Brn_ID,
    sc.[วิชาเอก (th) ],
    sc.[วิชาเอก (en) ],
    sc.[จุดเด่นของหลักสูตร (th) ],
    sc.[จุดเด่นของหลักสูตร (en) ],
    sc.[คุณสมบัติของผุู้เข้าศึกษา (th) ],
    sc.[คุณสมบัติของผุู้เข้าศึกษา (en) ] ,
    sc.cur_type_th,
    sc.cur_type_i,
    sc.cur_desth,
    sc.[อาชีพที่สามารถประกอบได้หลังสำเร็จการศึกษา (th) ] ,
    sc.[อาชีพที่สามารถประกอบได้หลังสำเร็จการศึกษา (en) ] ,
    sc.groupN_id ,
    sc.[กลุ่มการศึกษาแบ่งตามมหาวิทยาลัย (3 กลุ่ม) ]  AS study_group_type,
    sc.[ภาษาที่ใช้ทำวิทยานิพนธ์ (T/E) ] 
FROM
dbo.ICT_curriculum sc
WHERE  NOT EXISTS (
    SELECT 1
    FROM bronze.curriculum bc
    WHERE sc.cur_id = bc.cur_id
);
